# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libproj-dev
    - libgdal-dev

r_packages:
  - covr

r_github_packages:
  - MangoTheCat/visualTest

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
